# Generated by Django 4.2.4 on 2024-11-25 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArBooks',
            fields=[
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('z', models.IntegerField(blank=True, null=True)),
                ('standard_time', models.BigIntegerField(blank=True, null=True)),
                ('timeout', models.BigIntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.BigIntegerField(blank=True, null=True)),
                ('modification_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArRoles',
            fields=[
                ('role_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('control', models.CharField(max_length=1)),
                ('creation_date', models.DateField()),
                ('update_date', models.DateField(blank=True, null=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArStatus',
            fields=[
                ('status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('short_name', models.CharField(max_length=3)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.BigIntegerField(blank=True, null=True)),
                ('modification_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArSystems',
            fields=[
                ('system_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('url', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('creation_date', models.DateField()),
                ('update_date', models.DateField(blank=True, null=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArUsers',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=300)),
                ('additional_emails', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('blocked', models.BooleanField(default=False)),
                ('country_code', models.CharField(max_length=4)),
                ('state_code', models.CharField(blank=True, max_length=4, null=True)),
                ('city_code', models.CharField(blank=True, max_length=4, null=True)),
                ('recovery_timeout', models.DateTimeField(blank=True, null=True)),
                ('failed_auth', models.IntegerField(default=0)),
                ('super_user', models.BooleanField(default=False)),
                ('creation_date', models.DateField()),
                ('update_date', models.DateField(blank=True, null=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArUserRoles',
            fields=[
                ('user_role_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activation_date', models.DateField()),
                ('disable_date', models.DateField(blank=True, null=True)),
                ('creation_date', models.DateField()),
                ('update_date', models.DateField(blank=True, null=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fauapp.arroles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fauapp.arusers')),
            ],
        ),
        migrations.CreateModel(
            name='ArSystemOptions',
            fields=[
                ('option_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('url', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('activation_date', models.DateField()),
                ('disable_date', models.DateField(blank=True, null=True)),
                ('menu', models.BooleanField(blank=True, null=True)),
                ('sequence', models.BigIntegerField(blank=True, null=True)),
                ('icon_svg', models.CharField(blank=True, max_length=2000, null=True)),
                ('creation_date', models.DateField()),
                ('update_date', models.DateField(blank=True, null=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('parent_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fauapp.arsystemoptions')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fauapp.arsystems')),
            ],
        ),
        migrations.CreateModel(
            name='ArRoleOptions',
            fields=[
                ('role_option_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('activation_date', models.DateField()),
                ('disable_date', models.DateField(blank=True, null=True)),
                ('creation_date', models.DateField()),
                ('update_date', models.DateField(blank=True, null=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fauapp.arsystemoptions')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fauapp.arroles')),
            ],
        ),
        migrations.CreateModel(
            name='ArDeliveries',
            fields=[
                ('delivery_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.BigIntegerField(blank=True, null=True)),
                ('modification_date', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fauapp.arbooks')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fauapp.arstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fauapp.arusers')),
            ],
        ),
    ]
