# Generated by Django 4.2.4 on 2024-11-26 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fauapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ardeliveries',
            name='book',
            field=models.ForeignKey(db_column='book_isbn', on_delete=django.db.models.deletion.DO_NOTHING, to='fauapp.arbooks'),
        ),
        migrations.AlterField(
            model_name='ardeliveries',
            name='status',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.DO_NOTHING, to='fauapp.arstatus'),
        ),
        migrations.AlterField(
            model_name='ardeliveries',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='fauapp.arusers'),
        ),
        migrations.AlterField(
            model_name='arroleoptions',
            name='option',
            field=models.ForeignKey(db_column='option_id', on_delete=django.db.models.deletion.DO_NOTHING, to='fauapp.arsystemoptions'),
        ),
        migrations.AlterField(
            model_name='arroleoptions',
            name='role',
            field=models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.DO_NOTHING, to='fauapp.arroles'),
        ),
        migrations.AlterField(
            model_name='arsystemoptions',
            name='parent_option',
            field=models.ForeignKey(blank=True, db_column='parent_option_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fauapp.arsystemoptions'),
        ),
        migrations.AlterField(
            model_name='arsystemoptions',
            name='system',
            field=models.ForeignKey(db_column='system_id', on_delete=django.db.models.deletion.CASCADE, to='fauapp.arsystems'),
        ),
        migrations.AlterField(
            model_name='aruserroles',
            name='role',
            field=models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.DO_NOTHING, to='fauapp.arroles'),
        ),
        migrations.AlterField(
            model_name='aruserroles',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='fauapp.arusers'),
        ),
        migrations.AlterModelTable(
            name='arbooks',
            table='ar_books',
        ),
        migrations.AlterModelTable(
            name='ardeliveries',
            table='ar_deliveries',
        ),
        migrations.AlterModelTable(
            name='arroleoptions',
            table='ar_role_options',
        ),
        migrations.AlterModelTable(
            name='arroles',
            table='ar_roles',
        ),
        migrations.AlterModelTable(
            name='arstatus',
            table='ar_status',
        ),
        migrations.AlterModelTable(
            name='arsystemoptions',
            table='ar_system_options',
        ),
        migrations.AlterModelTable(
            name='arsystems',
            table='ar_systems',
        ),
        migrations.AlterModelTable(
            name='aruserroles',
            table='ar_user_roles',
        ),
        migrations.AlterModelTable(
            name='arusers',
            table='ar_users',
        ),
    ]
